exclude:
  - bin
  - lib
  - tmp
  - Gemfile
  - Gemfile.lock
  - node_modules

defaults:
  - scope:
      type: "pages"
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "post"
      permalink: /articles/:title

collections:
  pages:
    output: true
    permalink: /:name
  articles:
    output: false
    sort_by: date
  projects:
    output: false
    sort_by: priority

title: Patrick Reagan
