permalink: /essays/:title

defaults:
  - scope:
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    permalink: /:name
  articles:
    output: false
    sort_by: date
  projects:
    output: false
    sort_by: priority
